"""Add import-status tracking fields to UploadedCSV.

Generated by code change to support import progress and error messages.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('importing', 'Importing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='status_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsv',
            name='subscriptions_created',
            field=models.IntegerField(default=0),
        ),
    ]
