name: E2E Playwright tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e:
    runs-on: windows-latest
    env:
      JARVIS_COOKIE_SAMESITE: 'None'
      JARVIS_COOKIE_SECURE: 'true'
      # Optionally set domain if needed: JARVIS_COOKIE_DOMAIN: 'localhost'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node deps
        working-directory: client
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Build client
        working-directory: client
        run: npm run build

      - name: Run Django migrations
        run: |
          python manage.py migrate --noinput

      - name: Start servers (background)
        run: |
          Start-Process -NoNewWindow -FilePath python -ArgumentList 'manage.py','runserver','127.0.0.1:8000'
          Start-Process -NoNewWindow -FilePath npx -ArgumentList 'http-server','client/build','-p','3000'
          Start-Sleep -s 5

      - name: Run Playwright tests
        working-directory: client
        run: npx playwright test --project=chromium --reporter=list --workers=1

      - name: Upload test-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: client/test-results
