name: Playwright E2E

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d test" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        env:
          DB_NAME: test
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
        run: |
          python manage.py migrate --noinput
      - name: Start Django
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 3
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install client deps
        working-directory: client
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          E2E_BASE_URL: http://localhost:3000
        working-directory: client
        run: |
          npm run build
          npx serve -s build -l 3000 &
          sleep 2
          npm run e2e:ci
